apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pull-request-gitops
  title: Repo GitOps Service ECS PR
  description: Template para criar um novo pull request no repositório de GitOps
spec:
  owner: hype/infra
  type: service

  parameters:
    - title: Nome do Serviço a ser criado
      required:
        - service
        - clusterName
        - destroyService
        - environment
        - targetPath
      properties:
        service:
          title: Nome do Serviço
          type: string
          description: Nome do serviço a ser criado
          ui:field: EntityNamePicker
          ui:autofocus: true
        clusterName:
          title: Nome do Cluster
          type: string
          description: Selecionar cluster
          default: cluster-product
          enum:
            - cluster-product
            - cluster-devops
          enumNames:
            - 'cluster-product'
            - 'cluster-devops'
        destroyService:
          title: Deletar serviço via Terraform
          type: string
          description: Deletar serviço via Terraform
          default: 'false'
          enum:
            - 'false'
            - 'true'
          enumNames:
            - 'NÃO'
            - 'SIM'
        environment:
          title: Ambiente do Serviço
          type: string
          description: Ambiente onde o serviço será criado
          default: staging
          enum:
            - staging
            - production
          enumNames:
            - 'staging'
            - 'production'
        targetPath:
          title: Local a ser criado no repositório
          type: string
          description: Local onde o serviço será criado no repositório
          default: ./

    - title: Repositorio onde sera criado o PR
      required:
        - repoUrl
      properties:
        repoUrl:
          title: "Owner: Hype-Empreendimentos, Repository: gitops"
          description: URL do repositório onde o PR será criado
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./gitops
        copyWithoutRender:
          - .github/workflows/*
          - ecs-services/${{parameters.environment}}/${{parameters.service}}/aws_task_definition.tf
        values:
          name: ${{parameters.service}}
          environment: ${{parameters.environment}}
          cluster: ${{parameters.clusterName}}
          destroyService: ${{parameters.destroyService}}
          owner: ${{ parameters.repoUrl.split("=").join(" ").split("?").join("").split("&").join(" ").split(" ")[1] }}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        title: "Criando novo serviço: ${{parameters.service}} ${{parameters.clusterName}}-${{parameters.environment}}"
        repoUrl: ${{ parameters.repoUrl }}
        branchName: ${{parameters.service}}
        description: Criando serviço ${{parameters.service}}
        targetPath: ${{ parameters.targetPath if parameters.targetPath else parameters.service }}
        repository: "gitops"

  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        title: "Go to PR"