apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gitops
  description: "Criando serviço gitops"
  labels:
    system: web-apps
  tags:
    - terraform
    - gitops
  links:
    - url: https://github.com/${{ values.owner }}/gitops
      title: ${{ values.name }} no Service GitHub
      icon: code
  annotations:
    opsgenie.com/component-selector: 'tag:"service:gitops"'
    jenkins.io/github-folder: '${{ values.owner }}/gitops'
    fossa.io/project-name: ${{ values.name }}
    goharbor.io/repository-slug: '${{ values.owner }}/gitops'
    github.com/project-slug: '${{ values.owner }}/gitops'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest